version: '3'

services:
  server:
      build: ./
      image: pdf_encrypt_server:latest
      working_dir: /app
      command: "node index.js"
      restart: unless-stopped
      volumes:
        - "./app/:/app/"
        - "./data/:/data/"
      ports:
        - "1111:3000"
      environment:
        PORT: 3000
        DATA_DIR: /data
        PATH_TO_RUBY_ORIGAMI_GEM_PDFENCRYPT: /var/lib/gems/*/gems/origami-*/bin/pdfencrypt